from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd


ANALYSIS_ROOT = Path(__file__).resolve().parent
DEFAULT_CLEAN_DATASET = ANALYSIS_ROOT / "outputs" / "cleaned_data" / "02_clean_prices_no_outliers.csv"
DEFAULT_OUTPUT_DIR = ANALYSIS_ROOT / "outputs" / "app"
DEFAULT_RECOMMENDATIONS = ANALYSIS_ROOT / "outputs" / "tables" / "05_recommendations.csv"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export Data Analyst results as JSON files for dashboard and full-stack teams."
    )
    parser.add_argument(
        "--clean-dataset",
        default=DEFAULT_CLEAN_DATASET,
        type=Path,
        help="Path to the cleaned product dataset generated by notebook 02.",
    )
    parser.add_argument(
        "--output-dir",
        default=DEFAULT_OUTPUT_DIR,
        type=Path,
        help="Directory where dashboard-ready JSON files will be written.",
    )
    parser.add_argument(
        "--recommendations",
        default=DEFAULT_RECOMMENDATIONS,
        type=Path,
        help="Optional recommendations CSV generated by notebook 05.",
    )
    return parser.parse_args()


def read_clean_dataset(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Clean dataset not found: {path}. Run notebooks 01 and 02 before this export script."
        )

    df = pd.read_csv(path)
    required_columns = {"store", "category", "name", "price", "scraped_at"}
    missing = sorted(required_columns - set(df.columns))
    if missing:
        raise ValueError(f"Clean dataset is missing required columns: {missing}")

    df = df.copy()
    df["store"] = df["store"].astype(str).str.strip().str.lower()
    df["category"] = df["category"].astype(str).str.strip().str.lower()
    df["name"] = df["name"].astype(str).str.strip()
    df["price"] = pd.to_numeric(df["price"], errors="coerce")
    df["discount"] = pd.to_numeric(df.get("discount"), errors="coerce")
    df["stars"] = pd.to_numeric(df.get("stars"), errors="coerce")
    df["scraped_at"] = pd.to_datetime(df["scraped_at"], errors="coerce")
    df["scraped_date"] = pd.to_datetime(df.get("scraped_date", df["scraped_at"]), errors="coerce").dt.date
    df = df.dropna(subset=["store", "category", "name", "price", "scraped_at"])
    return df


def clean_records(dataframe: pd.DataFrame, decimals: int = 2) -> list[dict[str, Any]]:
    export_df = dataframe.copy()
    for column in export_df.select_dtypes(include=["float", "float64", "float32"]).columns:
        export_df[column] = export_df[column].round(decimals)
    for column in export_df.columns:
        if pd.api.types.is_datetime64_any_dtype(export_df[column]):
            export_df[column] = export_df[column].dt.strftime("%Y-%m-%dT%H:%M:%S")
    export_df = export_df.where(pd.notna(export_df), None)
    return export_df.to_dict(orient="records")


def write_json(path: Path, payload: dict[str, Any] | list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, default=str), encoding="utf-8")


def build_kpis(df: pd.DataFrame) -> dict[str, Any]:
    scrape_min = df["scraped_at"].min()
    scrape_max = df["scraped_at"].max()
    return {
        "total_products": int(len(df)),
        "total_stores": int(df["store"].nunique()),
        "total_categories": int(df["category"].nunique()),
        "average_price": round(float(df["price"].mean()), 2),
        "median_price": round(float(df["price"].median()), 2),
        "minimum_price": round(float(df["price"].min()), 2),
        "maximum_price": round(float(df["price"].max()), 2),
        "average_discount": round(float(df["discount"].dropna().mean()), 2)
        if df["discount"].notna().any()
        else None,
        "first_scrape": scrape_min.strftime("%Y-%m-%dT%H:%M:%S"),
        "last_scrape": scrape_max.strftime("%Y-%m-%dT%H:%M:%S"),
    }


def summarize_prices(df: pd.DataFrame, group_column: str) -> pd.DataFrame:
    return (
        df.groupby(group_column, dropna=False)["price"]
        .agg(
            products="count",
            average_price="mean",
            median_price="median",
            min_price="min",
            max_price="max",
            std_price="std",
        )
        .reset_index()
        .sort_values("median_price", ascending=True)
    )


def build_time_series(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.groupby(["scraped_date", "store"], dropna=False)["price"]
        .agg(products="count", average_price="mean", median_price="median")
        .reset_index()
        .sort_values(["scraped_date", "store"])
    )


def build_heatmap(df: pd.DataFrame) -> pd.DataFrame:
    return (
        df.groupby(["store", "category"], dropna=False)["price"]
        .agg(products="count", median_price="median", average_price="mean")
        .reset_index()
        .sort_values(["store", "category"])
    )


def build_top_discounts(df: pd.DataFrame, limit: int = 20) -> pd.DataFrame:
    if "discount" not in df.columns or df["discount"].dropna().empty:
        return pd.DataFrame(columns=["store", "category", "name", "price", "discount", "stars"])
    return (
        df.dropna(subset=["discount"])
        .sort_values("discount", ascending=False)
        .loc[:, ["store", "category", "name", "price", "discount", "stars"]]
        .head(limit)
    )


def read_recommendations(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    recommendations = pd.read_csv(path)
    return clean_records(recommendations)


def export_dashboard_files(clean_dataset: Path, output_dir: Path, recommendations_path: Path) -> list[Path]:
    df = read_clean_dataset(clean_dataset)
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    source_dataset = clean_dataset.resolve()
    try:
        source_label = str(source_dataset.relative_to(ANALYSIS_ROOT))
    except ValueError:
        source_label = str(source_dataset)

    files: dict[str, Any] = {
        "kpis.json": {
            "generated_at": generated_at,
            "source_file": source_label,
            "data": build_kpis(df),
        },
        "price_by_store.json": {
            "generated_at": generated_at,
            "data": clean_records(summarize_prices(df, "store")),
        },
        "price_by_category.json": {
            "generated_at": generated_at,
            "data": clean_records(summarize_prices(df, "category")),
        },
        "time_series_by_store.json": {
            "generated_at": generated_at,
            "data": clean_records(build_time_series(df)),
        },
        "heatmap_store_category.json": {
            "generated_at": generated_at,
            "data": clean_records(build_heatmap(df)),
        },
        "top_discounts.json": {
            "generated_at": generated_at,
            "data": clean_records(build_top_discounts(df)),
        },
        "recommendations.json": {
            "generated_at": generated_at,
            "data": read_recommendations(recommendations_path),
        },
    }

    manifest = {
        "generated_at": generated_at,
        "purpose": "Dashboard and full-stack consumption of Data Analyst outputs.",
        "source_dataset": source_label,
        "record_count": int(len(df)),
        "files": sorted(files.keys()),
        "contract": {
            "kpis.json": "Single object with global KPIs.",
            "price_by_store.json": "Array grouped by store/platform.",
            "price_by_category.json": "Array grouped by product category.",
            "time_series_by_store.json": "Array grouped by scraped_date and store.",
            "heatmap_store_category.json": "Array grouped by store and category.",
            "top_discounts.json": "Top discounted products for UI tables.",
            "recommendations.json": "Business recommendations from final insights.",
        },
    }
    files["manifest.json"] = manifest

    written: list[Path] = []
    for filename, payload in files.items():
        path = output_dir / filename
        write_json(path, payload)
        written.append(path)
    return written


def main() -> None:
    args = parse_args()
    written = export_dashboard_files(args.clean_dataset, args.output_dir, args.recommendations)
    print("Dashboard exports generated:")
    for path in written:
        print(f"- {path}")


if __name__ == "__main__":
    main()
