from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import pandas as pd


ANALYSIS_ROOT = Path(__file__).resolve().parent
DEFAULT_APP_OUTPUTS = ANALYSIS_ROOT / "outputs" / "app"
DEFAULT_PROJECT = "price-intelligence-495411"
DEFAULT_DATASET = "price_intelligence"

EXPORT_TABLES = {
    "kpis.json": "analytics_kpis",
    "price_by_store.json": "analytics_price_by_store",
    "price_by_category.json": "analytics_price_by_category",
    "time_series_by_store.json": "analytics_time_series_by_store",
    "heatmap_store_category.json": "analytics_heatmap_store_category",
    "top_discounts.json": "analytics_top_discounts",
    "recommendations.json": "analytics_recommendations",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upload Data Analyst dashboard exports from outputs/app to BigQuery analytics tables."
    )
    parser.add_argument("--project", default=DEFAULT_PROJECT, help="GCP project ID.")
    parser.add_argument("--dataset", default=DEFAULT_DATASET, help="BigQuery dataset name.")
    parser.add_argument(
        "--app-outputs",
        type=Path,
        default=DEFAULT_APP_OUTPUTS,
        help="Directory containing JSON files generated by export_for_dashboard.py.",
    )
    parser.add_argument(
        "--location",
        default=None,
        help="Optional BigQuery location, for example US or EU.",
    )
    parser.add_argument(
        "--write-disposition",
        choices=["WRITE_TRUNCATE", "WRITE_APPEND"],
        default="WRITE_TRUNCATE",
        help="WRITE_TRUNCATE replaces analytics tables; WRITE_APPEND appends rows.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate files and show planned uploads without writing to BigQuery.",
    )
    return parser.parse_args()


def read_payload(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Missing dashboard export: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def payload_to_dataframe(filename: str, payload: dict[str, Any]) -> pd.DataFrame:
    generated_at = payload.get("generated_at")

    if filename == "kpis.json":
        row = dict(payload.get("data") or {})
        row["generated_at"] = generated_at
        row["source_file"] = payload.get("source_file")
        return pd.DataFrame([row])

    rows = payload.get("data") or []
    if not isinstance(rows, list):
        raise ValueError(f"{filename} must contain a list under the 'data' key.")

    dataframe = pd.DataFrame(rows)
    if dataframe.empty:
        dataframe = pd.DataFrame(columns=["generated_at"])
    dataframe.insert(0, "generated_at", generated_at)
    return dataframe


def normalize_dataframe(dataframe: pd.DataFrame) -> pd.DataFrame:
    normalized = dataframe.copy()
    for column in normalized.columns:
        if normalized[column].map(lambda value: isinstance(value, (dict, list))).any():
            normalized[column] = normalized[column].map(
                lambda value: json.dumps(value, ensure_ascii=False) if isinstance(value, (dict, list)) else value
            )
    return normalized.where(pd.notna(normalized), None)


def build_upload_plan(app_outputs: Path) -> list[tuple[str, str, pd.DataFrame]]:
    plan: list[tuple[str, str, pd.DataFrame]] = []
    for filename, table_name in EXPORT_TABLES.items():
        payload = read_payload(app_outputs / filename)
        dataframe = normalize_dataframe(payload_to_dataframe(filename, payload))
        plan.append((filename, table_name, dataframe))
    return plan


def ensure_dataset(client: Any, project: str, dataset: str, location: str | None) -> Any:
    from google.cloud import bigquery

    dataset_id = f"{project}.{dataset}"
    dataset_ref = bigquery.Dataset(dataset_id)
    if location:
        dataset_ref.location = location
    return client.create_dataset(dataset_ref, exists_ok=True)


def upload_dataframe(
    client: Any,
    dataframe: pd.DataFrame,
    table_id: str,
    write_disposition: str,
) -> int:
    from google.cloud import bigquery

    job_config = bigquery.LoadJobConfig(
        autodetect=True,
        write_disposition=write_disposition,
    )
    job = client.load_table_from_dataframe(dataframe, table_id, job_config=job_config)
    job.result()
    table = client.get_table(table_id)
    return int(table.num_rows)


def main() -> None:
    args = parse_args()
    plan = build_upload_plan(args.app_outputs)

    print("BigQuery analytics upload plan")
    print("=" * 40)
    print(f"Project:   {args.project}")
    print(f"Dataset:   {args.dataset}")
    print(f"Source:    {args.app_outputs}")
    print(f"Mode:      {'DRY RUN' if args.dry_run else args.write_disposition}")
    print()

    for filename, table_name, dataframe in plan:
        print(f"- {filename} -> {args.project}.{args.dataset}.{table_name} ({len(dataframe)} rows)")

    if args.dry_run:
        print("\nDry run completed. No BigQuery table was modified.")
        return

    try:
        from google.cloud import bigquery
    except ImportError as exc:
        raise SystemExit("google-cloud-bigquery is not installed. Run: pip install -r data-analysis/requirements.txt") from exc

    client = bigquery.Client(project=args.project)
    ensure_dataset(client, args.project, args.dataset, args.location)

    print("\nUploading to BigQuery...")
    for _, table_name, dataframe in plan:
        table_id = f"{args.project}.{args.dataset}.{table_name}"
        row_count = upload_dataframe(client, dataframe, table_id, args.write_disposition)
        print(f"Uploaded {len(dataframe)} rows to {table_id}. Table now has {row_count} rows.")

    print("\nUpload completed successfully.")


if __name__ == "__main__":
    main()
